### ISSUE TITLE
Erro de Conexão - "could not connect: dial tcp :9009: connect: connection refused"

### ISSUE THREAD

**Issue by felpsgaya** [caarlos0/homekit-amt8000#10]
Olá @caarlos0,

Espero que esteja tudo bem. Primeiramente, gostaria de agradecer pelo seu trabalho no projeto.

Estou enfrentando um problema ao tentar conectar o sistema ao meu sistema de alarme Intelbras AMT8000. Já configurei o endereço IP correto, a porta correta e as senhas (master, instalador e configuração remota) de acordo com as instruções fornecidas. No entanto, continuo recebendo o seguinte erro:

```
5:17PM ERRO homekit: command to central failed err="could not init isecnet2 client: could not connect: dial tcp :9009: connect: connection refused"
```

Isso parece indicar um problema de conexão, onde o sistema não consegue estabelecer uma conexão com o endereço IP e a porta configurados. Já verifiquei as configurações várias vezes, e tudo parece estar correto.

Você teria alguma orientação ou sugestões sobre como resolver esse problema? Já verifiquei a documentação do sistema de alarme, e tudo parece estar configurado corretamente.

Agradeço antecipadamente pela sua ajuda!

**Comment by caarlos0** [comment]
variavel HOST não foi setada corretamente, provavelmente esta em branco.

dito isso, conforme readme, não dou suporte, soh esta publico o codigo pra quem quiser usar.
