### ISSUE TITLE
Problema com a Instalação do Plugin homekit-amt8000

### ISSUE THREAD

**Issue by felpsgaya** [caarlos0/homekit-amt8000#9]
Olá pessoal,

Estou enfrentando dificuldades na instalação e configuração do plugin **homekit-amt8000**. Eu segui as instruções do README, incluindo:

Utilizei o comando **npm install -g https://github.com/caarlos0/homekit-amt8000.git** para instalar o plugin.
Confirmei que o Homebridge está em execução e possui permissões adequadas.

Modifiquei o arquivo **config.json** conforme as orientações do README, incluindo todas as informações necessárias.

No entanto, ao reiniciar o Homebridge, o plugin não é reconhecido, e recebo a mensagem "No plugin was found for the platform 'amt8000' in your config.json."

Tentei várias soluções sugeridas, incluindo limpar o cache do npm, reinstalar o npm, verificar as permissões e seguir as instruções de instalação alternativas, mas o problema persiste.

Alguém já enfrentou esse problema ou teria alguma orientação adicional? Eu realmente aprecio qualquer ajuda ou insights que possam fornecer.

Obrigado!

**Comment by caarlos0** [comment]
esse projeto NÃO É um plugin pro homebridge, e não tem json nenhum de configuracao.
